/// Flutter icons MovementCustom
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MovementCustom
///      fonts:
///       - asset: fonts/MovementCustom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MovementCustom {
  MovementCustom._();

  static const _kFontFam = 'MovementCustom';
  static const _kFontPkg = null;

  static const IconData clap = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clap_fill = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_comment = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
